apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- serviceaccount.yaml
- servicemonitor.yaml

images:
- name: 569946568662.dkr.ecr.ap-southeast-1.amazonaws.com/fintrack/backend
  newTag: 71307a3706828969a33d50b93c817906586218a7
