apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fintrack
  namespace: argocd
spec:
  description: Fintrack Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: application
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'