apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: fintrack/db/credentials
      property: username
  - secretKey: password
    remoteRef:
      key: fintrack/db/credentials
      property: password
  - secretKey: host
    remoteRef:
      key: fintrack/db/credentials
      property: host
  - secretKey: port
    remoteRef:
      key: fintrack/db/credentials
      property: port
  - secretKey: database
    remoteRef:
      key: fintrack/db/credentials
      property: database
  - secretKey: url
    remoteRef:
      key: fintrack/db/credentials
      property: url

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: fintrack/app/secrets
      property: jwt_secret
  - secretKey: api_key
    remoteRef:
      key: fintrack/app/secrets
      property: api_key
  - secretKey: cors_allowed_origins
    remoteRef:
      key: fintrack/app/secrets
      property: cors_allowed_origins