apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: application
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::569946568662:role/fintrack-external-secrets
